language: php

sudo: false

branches:
  only:
    - master

php:
  - 7.2
  - 7.3

env:
  matrix:
    fast_finish: true

    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
    - composer test
